export const MIN_INCREMENT = 1; // Min increment amount
export const MAX_USERS_PER_DAY = 100; // Max users per day
export const MAX_INCREMENT = 5; // Max increment amount
export const MIN_INTERVAL_MS = 30 * 1000; // Min interval: 30 seconds
export const MAX_INTERVAL_MS = 15 * 60 * 1000; // Max interval: 15 minutes
export const TOTAL_TARGET_COUNT = 1500; // Max counter value
export const INCREMENT_START_HOUR = 6; // Start increment at 6 AM UTC
export const INCREMENT_END_HOUR = 22; // End increment at 10 PM UTC
export const PEAK_START_HOUR = 12; // 12 PM UTC
export const PEAK_END_HOUR = 14; // 2 PM UTC
export const PEAK_MIN_INCREMENT = 3;
export const PEAK_MAX_INCREMENT = 7;
export const MAX_COMMANDS_PER_DAY = 10000; // Max Redis commands per day
